src/components/JdsInputText/InputText.stories.js
=> remove console statement in InputText component

src/components/JdsButton/Button.vue
- Refactor class variant jds button component
- Added event on jds button component
=> JDS Button Component

src/components/JdsButton/Button.vue
- Added event on JDS Button Component
- Refactor class variant JDS Button Component
=> Component JDS Button

.github/workflows/chromatic.yml, package.json, playgrounds/vue/main.js, scripts/build-esm.js, scripts/build-icons.js, src/components/JdsAccordion/Accordion.scss, src/components/JdsBadge/Badge.scss, src/components/JdsButton/Button.scss, src/components/JdsCalendar/Calendar.scss, src/components/JdsCheckbox/Checkbox.scss, src/components/JdsCheckboxGroup/CheckboxGroup.scss, src/components/JdsCheckboxToggle/CheckboxToggle.scss, src/components/JdsDateInput/DateInput.scss, src/components/JdsFormControl/FormControlErrorMessage.vue, src/components/JdsFormControl/FormControlHelperText.vue, src/components/JdsFormControl/FormControlLabel.vue, src/components/JdsIcon/Icon.vue, src/components/JdsInputText/InputText.scss, src/components/JdsInputTextEdge/InputTextEdge.scss, src/components/JdsOptions/Options.scss, src/components/JdsRadioButton/RadioButton.scss, src/components/JdsSelect/Select.scss, src/components/JdsSimpleTable/SimpleTable.scss, src/components/JdsTextArea/TextArea.scss, src/components/JdsToggle/Toggle.scss, vue.config.js
- SCSS import shouldn't use `~` or module resolve alias, because it is actually webpack feature.
- Create script to convert SVG icons to Vue component at build time.
=> Fix stylesheet 

publish/package.json
- Increment version
- Added keyword
- Setup url github
- Added dependencies sass loader
=> Setup publish package

src/components/JdsOptions/Options.scss
- Add hover state styling on option list item element
=> JdsOptions: ensure option text color is changed on hovered

publish/package.json
- Added dependencies babel plugin proposan nullish coalescing and optional chaining
=> Added dependencies babel plugin proposal nullish coalescing and optional chaining

publish/package.json
- Changed sideEffects value in package.json
- Increment package version
=> Changed sideEffects value in package.json

src/components/JdsCard/Card.scss
- use relative path for SCSS import
=> JdsCard: use relative import path

src/storybook-docs/desaintoken.stories.mdx, src/storybook-docs/installation.stories.mdx
=> Added docs installation

package.json, publish/package.json
- Added script release
- Increment package version
=> Added script release

src/components/JdsDataTable/DataTable.scss, src/components/JdsDataTable/DataTable.vue
[Developer Handoff](https://www.figma.com/file/ApxYqXtPhfP4hAlWkUGl4I/JDS---Desktop-Components?node-id=9418%3A88313) of Data Table Components
**Loading State**
**Empty State**
=> Feature: Empty State and Loading State

.github/ISSUE_TEMPLATE/feature_request.md
**Apakah permintaan fitur berawal dari kesulitan penggunaan library? Coba jelaskan.**
Jelaskan secara jelas dan singkat apa kesulitan yang kamu hadapi ketika menggunakan *library* **JDS Design System**. Contoh. Saya selalu frustasi ketika ingin melakukan [...].
**Jelaskan solusi yang anda inginkan**
Jelaskan secara jelas dan deskripsikan secara singkat solusi apa yang kamu inginkan. Contoh. Saya ingin komponen calendar JDS Design System bisa sama prilakunya dengan komponen calendar Carbon Design System.
**Jelaskan solusi alternatif yang anda pertimbangkan**
Jelaskan secara jelas dan deskripsikan secara singkat solusi alternatif apa yang kamu pertimbangkan. Contoh. Sebaiknya untuk properti `min max range` pada komponen `date input`  dihilangkan dahulu jika memang belum tersedia. …
=> Add feature request issues template

src/components/JdsPagination/Pagination.stories.js, src/components/JdsPagination/Pagination.vue
- Change `itemsPerPage` and `itemsPerPageOptions` default value in compliance with [Jds Pagination Acceptance Criteria](https://www.figma.com/file/ApxYqXtPhfP4hAlWkUGl4I/JDS---Desktop-Components?node-id=9725%3A94301)
=> Change Props Default Value

src/components/JdsButton/Button.vue
- Remove emit and make component transparent
title: Membuat komponen button menjadi transparan 
project: Jabar Design System
participants: @adzharamrullah @adrianpdm @Ibwedagama @bangunbagustapa @yoslie
=> Remove emit and make component button transparent

src/components/JdsToggle/Toggle.stories.js
- Add storybook template variant for toggle component
title: Add storybook template variant for toggle component
project: Jabar Design System
participants: @bangunbagustapa @adzharamrullah @adrianpdm @Ibwedagama @maruf_harsono
=> Add storybook template variant for toggle component

src/components/JdsButton/Button.scss, src/components/JdsButton/Button.vue
- Fixed glitch component JDS Button
title: Fixed glitch component JDS Button
Project: Jabar Design System
participants: @adrianpdm @Ibwedagama @ArifWicakSon @yoslie @bangunbagustapa @maulanayuseph
=> Fixed glitch component JDS Button

src/storybook-docs/installation.stories.mdx
- Add notes to docs storybook
title: Add notes to docs storybook
projects: Jabar Design System
participants: @adzharamrullah @adrianpdm @yoslie @bangunbagustapa @Ibwedagama @maruf_harsono
=> Add notes to docs storybook

publish/package.json
- fix : add lodash orderby to library dependencies
title: fix : add lodash orderby to library dependencies
project: Jabar Design System
participants: @adzharamrullah @Ibwedagama
=> fix : add lodash orderby to library dependencies

publish/package.json, src/utils/date-input.js
- fix: don't force esm module import imask
title: fix: don't force esm module import imask
project: Jabar Design System
participants: @adzharamrullah @Ibwedagama
=> Fix esm import lib imask
